var $loader = $('<div class="alert alert-info" id="loading-alert"><p>Retrieving Results<p><img src="img/preloader.gif" alt="Retrieving Results Now" /></div>');
var $no_results = $('<div class="alert alert-info" id="no-result-alert">No results were found for this query.</div>');
var $filter = $('#filter-used');
var $browse = $('#browse-menu');
var $search_results = $('#search-results');
var $browse_btn = $('#browse-button');
var $semester = $('#strm');
var $session_codes = $('#session');
var $auto_subject = $('#auto-subject');
var $expand_form = $('#expand-form');
var $expand_icon = $('#expand-icon');
var $adv_link = $('#show-adv-link');
var $details_modal = $('#details-modal');
var $course_units = $('#course-units');
var $course_career = $('#course-career');
var $course_descr = $('#course-descr');
var $course_reqs = $('#course-reqs');
var $course_link = $('#course-link');
var $course_attr = $('#course-attr');
var $course_sem = $('#course-sem');
var $course_title = $('#modalTitle');
